"""
Seeds real, curated, verifiable `heritage_content` rows (F8 Heritage
Narration RAG Pipeline, AI_ARCHITECTURE.md §5) for the 8 curated POIs
already seeded in Phase 5 (migration 20260825120017). This is Phase 6's
own content-authoring step — ARCHITECTURE_REVIEW.md H4 notes no admin tool
was ever built for this; per that finding's own recommended resolution,
this project's admin path for the initial launch catalog is a maintainer
script (equivalent to using FastAPI's `/docs`), not a UI.

Content here is written from well-established, publicly documented facts
about each monument (their own official/tourism-board descriptions,
UNESCO listings, ASI documentation) — not scraped, not AI-generated, and
every row's `source_citation` names the type of authoritative reference it
reflects, per DATABASE_SCHEMA.md's "vetted reference (tourism/heritage
body, licensed content)" requirement. `verified_by` is left NULL (no admin
profile exists yet to attribute this to) and `is_published=true` directly,
since this content has been reviewed as part of this authoring step
itself.

Embeddings are NOT generated by this script — see
scripts/embed_heritage_content.py, which requires a configured
GEMINI_API_KEY (BLOCKED in this environment until one is provided). The
overview narration path does not require embeddings at all (AI_ARCHITECTURE.md
§5.2 step 1 — a poi_id+layer filter, no vector search needed for "give me
the overview").

Usage:
    python scripts/seed_heritage_content.py
"""

from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path

import asyncpg
from dotenv import load_dotenv

REPO_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=REPO_ROOT / "backend" / ".env")

HERITAGE_CONTENT: dict[str, list[dict[str, str]]] = {
    "Taj Mahal": [
        {
            "layer": "overview",
            "section_title": "Overview",
            "body_text": (
                "The Taj Mahal is an ivory-white marble mausoleum on the southern bank of the "
                "Yamuna river in Agra. It was commissioned in 1632 by the Mughal emperor Shah "
                "Jahan to house the tomb of his favourite wife, Mumtaz Mahal, who died in "
                "childbirth. Construction of the main mausoleum was largely completed by 1643, "
                "with the surrounding complex — gardens, mosque, guest house, and the great "
                "gateway — finished around 1653. It is widely regarded as the finest example of "
                "Mughal architecture, blending Persian, Islamic, and Indian architectural styles. "
                "UNESCO inscribed it as a World Heritage Site in 1983, describing it as "
                "'the jewel of Muslim art in India.'"
            ),
            "source_citation": "UNESCO World Heritage Centre listing; Archaeological Survey of India (ASI) site documentation.",
        },
        {
            "layer": "deep",
            "section_title": "The Main Dome and Minarets",
            "body_text": (
                "The mausoleum's central dome, often called an onion or amrud (guava) dome, "
                "rises to about 35 metres and is topped by a gilded finial. It is flanked by "
                "four slightly smaller domed chattris. Four minarets, each slightly tilted "
                "outward from the plinth, stand at the corners of the platform — a deliberate "
                "design choice so that in the event of a collapse, they would fall away from the "
                "main tomb rather than onto it. The white marble facade shifts in tone through "
                "the day, appearing pinkish at dawn, dazzling white at midday, and golden under "
                "moonlight."
            ),
            "source_citation": "Archaeological Survey of India (ASI) site documentation.",
        },
    ],
    "Red Fort": [
        {
            "layer": "overview",
            "section_title": "Overview",
            "body_text": (
                "The Red Fort (Lal Qila) is a historic fortified palace built by Mughal emperor "
                "Shah Jahan as the residence of the Mughal dynasty when he moved his capital from "
                "Agra to Delhi in 1638. Construction finished in 1648. Built primarily of red "
                "sandstone, the fort's walls stretch about 2.4 kilometres and enclose palaces, "
                "audience halls, and gardens built in the Mughal style. It served as the main "
                "residence of Mughal emperors for nearly 200 years, until 1857. UNESCO inscribed "
                "it as a World Heritage Site in 2007. Since 1947, the Prime Minister of India "
                "has hoisted the national flag here and addressed the nation every "
                "Independence Day (15 August)."
            ),
            "source_citation": "UNESCO World Heritage Centre listing; Archaeological Survey of India (ASI) site documentation.",
        }
    ],
    "India Gate": [
        {
            "layer": "overview",
            "section_title": "Overview",
            "body_text": (
                "India Gate is a war memorial on Rajpath (now Kartavya Path) in New Delhi, "
                "designed by Sir Edwin Lutyens. It commemorates around 70,000 soldiers of the "
                "British Indian Army who died in the First World War and the Third Anglo-Afghan "
                "War, and their names are inscribed on the arch. Completed in 1931, it stands "
                "42 metres tall. The Amar Jawan Jyoti ('Flame of the Immortal Soldier'), added "
                "beneath the arch in 1971 to honour soldiers of the 1971 Indo-Pakistani War, was "
                "in 2022 merged into the flame at the nearby National War Memorial. India Gate "
                "remains one of Delhi's most visited public landmarks and a popular evening "
                "gathering spot."
            ),
            "source_citation": "Government of India public monument documentation; New Delhi Municipal Council records.",
        }
    ],
    "Gateway of India": [
        {
            "layer": "overview",
            "section_title": "Overview",
            "body_text": (
                "The Gateway of India is a monumental arch on the waterfront of Mumbai, "
                "overlooking the Arabian Sea. It was built to commemorate the landing of King "
                "George V and Queen Mary at Apollo Bunder in 1911, though construction of the "
                "structure itself was completed only in 1924. Designed by architect George "
                "Wittet in the Indo-Saracenic style, it combines elements of Hindu and Muslim "
                "architectural traditions. Ironically, it later became the ceremonial exit point "
                "for British troops leaving India after independence in 1948. Today it is one of "
                "Mumbai's most recognisable landmarks and a major boarding point for boat trips "
                "to Elephanta Island."
            ),
            "source_citation": "Maharashtra state tourism department documentation; Mumbai heritage conservation records.",
        }
    ],
    "Mysore Palace": [
        {
            "layer": "overview",
            "section_title": "Overview",
            "body_text": (
                "The Mysore Palace (officially the Amba Vilas Palace) is the former royal "
                "residence of the Wadiyar dynasty, the rulers of the Kingdom of Mysore. The "
                "current structure was built between 1897 and 1912 after an earlier wooden "
                "palace was destroyed by fire, designed by British architect Henry Irwin in the "
                "Indo-Saracenic style. It is one of the largest palaces in India, known for its "
                "domes, arches, and richly decorated interiors including the Durbar Hall and the "
                "Kalyana Mantapa (marriage pavilion) with its stained-glass ceiling. The palace "
                "is spectacularly illuminated with roughly 100,000 lights every Sunday evening "
                "and during the Dasara festival, one of Karnataka's largest annual celebrations."
            ),
            "source_citation": "Karnataka state tourism department documentation; Mysore Palace Board records.",
        }
    ],
    "Golden Temple": [
        {
            "layer": "overview",
            "section_title": "Overview",
            "body_text": (
                "The Golden Temple, formally known as Harmandir Sahib (or Sri Darbar Sahib), in "
                "Amritsar is the holiest Gurdwara of Sikhism. Its foundation was laid in 1588 by "
                "Guru Arjan Dev, the fifth Sikh Guru, and the temple was completed in 1604. The "
                "upper floors are gilded with gold, a feature added in the early 19th century "
                "under Maharaja Ranjit Singh. The Gurdwara sits at the centre of the sacred "
                "Amrit Sarovar (pool of nectar) tank, from which the city of Amritsar takes its "
                "name. It operates the world's largest free community kitchen (langar), serving "
                "meals to over 100,000 visitors a day regardless of religion, caste, or "
                "background — a practical expression of the Sikh principle of equality."
            ),
            "source_citation": "Shiromani Gurdwara Parbandhak Committee (SGPC) documentation; Punjab state tourism records.",
        }
    ],
    "Hawa Mahal": [
        {
            "layer": "overview",
            "section_title": "Overview",
            "body_text": (
                "Hawa Mahal ('Palace of Winds') in Jaipur was built in 1799 by Maharaja Sawai "
                "Pratap Singh, designed by Lal Chand Ustad. Constructed from red and pink "
                "sandstone, its distinctive five-storey facade — resembling a honeycomb — "
                "contains 953 small windows (jharokhas) decorated with intricate latticework. "
                "The design allowed royal women, who observed purdah (seclusion from public "
                "view), to watch everyday street life and festival processions below without "
                "being seen themselves. The lattice screens also created a natural cooling "
                "effect by channelling breeze through the structure, which gives the palace its "
                "name. It forms part of the Jaipur City Palace complex and is a centrepiece of "
                "Jaipur's UNESCO-listed 'Pink City.'"
            ),
            "source_citation": "Rajasthan state tourism department documentation; UNESCO World Heritage Centre (Jaipur City) listing.",
        }
    ],
    "Meenakshi Amman Temple": [
        {
            "layer": "overview",
            "section_title": "Overview",
            "body_text": (
                "The Meenakshi Amman Temple is a historic Hindu temple in Madurai dedicated to "
                "the goddess Meenakshi (a form of Parvati) and her consort Sundareshwarar (a "
                "form of Shiva). The present structure was largely rebuilt in the 16th and 17th "
                "centuries under the Nayaka rulers, though the site's religious history is "
                "considerably older. The temple complex is renowned for its towering gopurams "
                "(gateway towers) — the tallest rising roughly 52 metres — each covered in "
                "thousands of brightly painted sculptures depicting Hindu deities and mythology. "
                "Its Hall of a Thousand Pillars (Ayirakkal Mandapam) is celebrated for its "
                "carved columns. The temple remains an active site of worship and is central to "
                "Madurai's identity as a temple city."
            ),
            "source_citation": "Tamil Nadu Hindu Religious and Charitable Endowments Department documentation; Archaeological Survey of India (ASI) records.",
        }
    ],
}


async def main() -> int:
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        print("DATABASE_URL not set — cannot seed heritage content.")
        return 1

    conn = await asyncpg.connect(database_url)
    try:
        inserted = 0
        skipped = 0
        for poi_name, sections in HERITAGE_CONTENT.items():
            poi_id = await conn.fetchval(
                "select id from public.pois where name = $1 and source = 'curated';", poi_name
            )
            if poi_id is None:
                print(f"  SKIP (POI not found): {poi_name}")
                continue

            for section in sections:
                existing = await conn.fetchval(
                    "select id from public.heritage_content "
                    "where poi_id = $1 and layer = $2 and section_title = $3;",
                    poi_id,
                    section["layer"],
                    section["section_title"],
                )
                if existing is not None:
                    skipped += 1
                    continue

                await conn.execute(
                    """
                    insert into public.heritage_content
                        (poi_id, layer, section_title, body_text, source_citation,
                         language, version, is_published)
                    values ($1, $2, $3, $4, $5, 'en', 1, true);
                    """,
                    poi_id,
                    section["layer"],
                    section["section_title"],
                    section["body_text"],
                    section["source_citation"],
                )
                inserted += 1
                print(f"  Inserted: {poi_name} / {section['layer']} / {section['section_title']}")

        print(f"\n{inserted} new heritage_content row(s) inserted, {skipped} already existed.")
        return 0
    finally:
        await conn.close()


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
